# .vuepress/config.yml
title: MinecraftHub
description: awa
base: /
themeConfig: 
  logo: /api/img/logo.svg
  nav:
    - text: 首页
      link: /home/
    - text: 资源导航
      link: /MC/Nav/
    - text: 关于我们
      link: /about/
    - text: GitHub
      link: https://github.com/AkizukiStudio/MinecraftHub/
  displayAllHeaders: true
